name: gh_pr_sync

on:
  workflow_dispatch:

  schedule:
    - cron: '@daily'

jobs:
  branch_sync:
    runs-on: codeberg-tiny
    container:
      image: 'data.forgejo.org/oci/node:20-bookworm'
    steps:
      - name: synchronize opened pull requests from Konflux
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PR_SYNC_TOKEN }} " \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/fedora-infra/forgejo-oci-images/pulls