name: gh_pr_sync

on:
  workflow_dispatch:

  schedule:
    - cron: '@daily'

jobs:
  gh_pr_sync:
    runs-on: codeberg-tiny
    container:
      image: 'data.forgejo.org/oci/node:20-bookworm'
    steps:
      - name: Set git identity
        run: |
          git config --global user.name "konflux-gh-forgejo-sync"
          git config --global user.email "konflux-gh-forgejo-sync@noarealdomain.org"

      - name: Get URL of the patch from latest GitHub PR
        run: |
          echo "PATCH_URL=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PR_SYNC_TOKEN }} " \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/fedora-infra/forgejo-oci-images/pulls > output.json && \
            node -p "!JSON.parse(require('fs').readFileSync('output.json')).length ? console.log('No new pullrequests') : JSON.parse(require('fs').readFileSync('output.json'))[0].patch_url ")" >> $GITHUB_ENV 
      - name: Fetch the PR as patch and apply
        run: |
          if [ -z "${{ env.PATCH_URL }}" ]; then
            echo "There are no new PRs from konflux bot"
          else
            echo "The GH patch URL is: ${{ env.PATCH_URL }}"
            git clone -b main https://${{secrets.FORGEJO_GIT_TOKEN}}@codeberg.org/fedora/oci-image-definitions.git
            cd oci-image-definitions
            curl -L ${{ env.PATCH_URL }} | git am
            git push 
          fi
          
